//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskFrontEnd.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRUEBA_HELP_DESKEntities : DbContext
    {
        public PRUEBA_HELP_DESKEntities()
            : base("name=PRUEBA_HELP_DESKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PR_ANEXOS> PR_ANEXOS { get; set; }
        public DbSet<PR_DEPARTMENTS> PR_DEPARTMENTS { get; set; }
        public DbSet<PR_PROBLEM> PR_PROBLEM { get; set; }
        public DbSet<PR_TICKET> PR_TICKET { get; set; }
        public DbSet<PR_TICKET_STATE> PR_TICKET_STATE { get; set; }
        public DbSet<PR_USER_FOLLOWED> PR_USER_FOLLOWED { get; set; }
        public DbSet<PR_USERS> PR_USERS { get; set; }
        public DbSet<PR_USERS_ROL> PR_USERS_ROL { get; set; }
    }
}
