//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskFrontEnd.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_DEPARTMENTS
    {
        public PR_DEPARTMENTS()
        {
            this.PR_TICKET = new HashSet<PR_TICKET>();
            this.PR_USERS = new HashSet<PR_USERS>();
        }
    
        public int ID_DEPARTMENT { get; set; }
        public string DEPARTMENT { get; set; }
    
        public virtual ICollection<PR_TICKET> PR_TICKET { get; set; }
        public virtual ICollection<PR_USERS> PR_USERS { get; set; }
    }
}
