//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskFrontEnd.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_TICKET
    {
        public PR_TICKET()
        {
            this.PR_ANEXOS = new HashSet<PR_ANEXOS>();
        }
    
        public int ID_TICKET { get; set; }
        public Nullable<int> USER_CREATED { get; set; }
        public Nullable<int> USER_ASIGNED { get; set; }
        public string DESCRIPCION { get; set; }
        public string COMMENTARY { get; set; }
        public Nullable<int> ID_PROBLEM { get; set; }
        public Nullable<int> ID_DEPARTMENT_ASIGNED { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> ID_STATE { get; set; }
    
        public virtual ICollection<PR_ANEXOS> PR_ANEXOS { get; set; }
        public virtual PR_DEPARTMENTS PR_DEPARTMENTS { get; set; }
        public virtual PR_PROBLEM PR_PROBLEM { get; set; }
        public virtual PR_TICKET_STATE PR_TICKET_STATE { get; set; }
        public virtual PR_USERS PR_USERS { get; set; }
        public virtual PR_USERS PR_USERS1 { get; set; }
    }
}
