//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskFrontEnd.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_USERS_ROL
    {
        public PR_USERS_ROL()
        {
            this.PR_USERS = new HashSet<PR_USERS>();
        }
    
        public int ID_ROL { get; set; }
        public string ROL { get; set; }
    
        public virtual ICollection<PR_USERS> PR_USERS { get; set; }
    }
}
