//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskBackend.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_ANEXOS
    {
        public int ID_ANEXO { get; set; }
        public Nullable<int> ID_TICKET { get; set; }
        public string FILES_NTEXT { get; set; }
    
        public virtual PR_TICKET PR_TICKET { get; set; }
    }
}
